hooks:
- hooks/mark_generated.py
edit_uri: edit/main/docs/
extra_css:
- css/qs.css
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 2-6
- md_in_html
nav:
- Home: index.md
- Getting Started:
  - getting-started/index.md
  - Installation: getting-started/installation.md
  - Getting Started: getting-started/getting-started.md
  - Concepts and Terminology: getting-started/concepts-and-terminology.md
  - Invoking Quicksilver: getting-started/invoking-quicksilver.md
- Features:
  - features/index.md
  - Files and Folders: features/Files and Folders.md
  - Applications and Processes: features/Applications and Processes.md
  - Contacts: features/Contacts.md
  - Mail: features/Mail.md
  - Chat: features/Chat.md
  - Calendar: features/Calendar.md
  - Web: features/Web.md
  - Text: features/Text.md
  - Triggers:
    - features/triggers/index.md
    - Types of Triggers:
      - Keyboard Triggers: features/triggers/keyboard-triggers.md
      - Mouse Triggers: features/triggers/mouse-triggers.md
      - Event Triggers: features/triggers/event-triggers.md
      - Gesture Triggers: features/triggers/gestures.md
    - Examples:
      - Example Triggers: features/triggers/examples.md
      - More Trigger Ideas: features/triggers/more-examples.md
  - Using the Mouse: features/using-the-mouse.md
  - Clipboard and Shelf: features/Clipboard and Shelf.md
  - Note Taking Applications: features/Note Taking Applications.md
  - Images: features/Images.md
  - System: features/System.md
  - Alternate Actions: features/alternate-actions.md
  - Finder Selection: features/finder-selection.md
  - Interfaces: features/interfaces.md
  - AppleScript:
    - features/applescript/index.md
    - Custom Actions: features/applescript/custom-actions.md
    - Action Templates: features/applescript/templates.md
    - Color Picker: features/applescript/color-picker.md
    - Convert Units: features/applescript/convert-units.md
    - Open AirDrop: features/applescript/open-airdrop.md
    - Paste File Path: features/applescript/paste-file-path.md
    - Run Shell Command: features/applescript/run-shell-command.md
  - Development: features/Development.md
- Plugins:
  - plugins/index.md
  - 1Password: plugins/onepassword.md
  - Abracadabra Triggers: plugins/gesturetriggers.md
  - Apple Mail: plugins/applemail.md
  - Audio: plugins/audio.md
  - Automator: plugins/automator.md
  - Calculator: plugins/tscalculator.md
  - Calendar & Reminders: plugins/icalmodule.md
  - Clipboard: plugins/clipboard.md
  - Command Line Tool: plugins/commandlinetool.md
  - Contacts: plugins/addressbook.md
  - Cyberduck: plugins/cyberduck.md
  - Dash: plugins/dash.md
  - DeMinimizer: plugins/ytdemin.md
  - Developer: plugins/developer.md
  - Displays: plugins/displays.md
  - E-mail Support: plugins/emailsupport.md
  - Emojis: plugins/emojisplugin.md
  - Event Triggers: plugins/eventtriggers.md
  - Extra Scripts: plugins/extrascripts.md
  - FaceTime: plugins/facetime.md
  - File Attribute: plugins/fileattributes.md
  - File Compression: plugins/compression.md
  - Firefox: plugins/firefox.md
  - Gmail: plugins/gmail.md
  - Google Chrome: plugins/googlechrome.md
  - Image Manipulation: plugins/imagemanipulation.md
  - iPhoto: plugins/iphoto.md
  - iTerm2: plugins/iterm2.md
  - iTunes: plugins/itunes.md
  - Keychain: plugins/keychain.md
  - MailMate: plugins/mailmate.md
  - Microsoft Office: plugins/microsoftoffice.md
  - Mouse Triggers: plugins/mousetrigger.md
  - Networking: plugins/networking.md
  - Nostromo Interface: plugins/nostromointerface.md
  - Notification Hub: plugins/notificationhub.md
  - OmniWeb: plugins/omniweb.md
  - OpenMeta File Tagging: plugins/openmetafiletagging.md
  - Opera: plugins/opera.md
  - Process Manipulation: plugins/processmanipulation.md
  - QSQRCode: plugins/qrcode.md
  - Remember The Milk: plugins/rememberthemilk.md
  - Remote Hosts: plugins/remotehosts.md
  - Safari: plugins/safari.md
  - Screen Capture: plugins/screencapture.md
  - Services Menu: plugins/servicesmenu.md
  - Shelf: plugins/shelf.md
  - Shortcuts: plugins/shortcutsplugin.md
  - Spotlight: plugins/spotlight.md
  - System HotKey Commands: plugins/symbolichotkey.md
  - Terminal: plugins/terminal.md
  - Text Manipulation: plugins/textmanipulation.md
  - Transmit 4: plugins/transmitmodule.md
  - Twitter: plugins/twit.md
  - User Interface: plugins/uiaccess.md
  - Viscosity: plugins/viscosity.md
  - Web Search: plugins/websearch.md
  - Yojimbo: plugins/yojimbo.md
  - Yosemite Interface: plugins/yosemite.md
  - zoom.us: plugins/zoom.md
- Preferences:
  - Overview: preferences/preferences.md
  - General: preferences/general.md
  - Catalog: preferences/catalog.md
  - Triggers: preferences/triggers.md
  - Actions: preferences/actions.md
  - Plugins: preferences/plugins.md
- Appendix:
  - appendix/index.md
  - FAQ: appendix/FAQ.md
  - Troubleshooting: appendix/Troubleshooting.md
  - Keyboard Shortcuts: appendix/keyboard-shortcuts.md
  - Hidden Defaults: appendix/hidden-defaults.md
  - Known Bad Applications: appendix/known-bad-applications.md
  - Tips: appendix/tips.md
  - Tutorials: appendix/tutorials.md
  - Extending Quicksilver: appendix/Extending Quicksilver.md
  - Random Notes: appendix/Random Notes.md
  - Touch Bar Support: appendix/touch-bar-support.md
  - Style Guide: appendix/Style Guide.md
plugins:
- git-committers:
    repository: quicksilver/manual
    branch: main
    token: !ENV [GIT_COMMITTERS_TOKEN]
    enabled: !ENV [CI, false]
    exclude:
    - plugins/*
- git-revision-date-localized:
    fallback_to_build_date: true
    type: timeago
- search:
    lang: en
- to-pdf:
    author: Howard Melman & Quicksilver Team
    cover_logo: https://qsapp.com/assets/quicksilver-icon-CpykCx5c.png
    cover_subtitle: !ENV [PDF_COVER_SUBTITLE, Quicksilver User Manual]
    copyright: "QSApp.com"
    download_link: footer
    enabled_if_env: BUILD_PDF
    output_path: pdf/quicksilver-manual.pdf
repo_url: https://github.com/quicksilver/manual
site_name: Quicksilver User Manual
site_url: https://qsapp.com/manual
theme:
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - navigation.indexes
  - navigation.footer
  - content.action.edit
  - search.suggest
  - search.highlight
  - search.share
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  locale: en
  name: material
  palette:
  - accent: purple
    primary: custom
    scheme: light
  - accent: purple
    primary: custom
    scheme: dark
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://qsapp.com
    - icon: fontawesome/solid/file-pdf
      link: https://qsapp.com/manual/pdf/quicksilver-manual.pdf
    - icon: fontawesome/brands/github
      link: https://github.com/quicksilver/quicksilver
