extra_css:
- css/qs.css
markdown_extensions:
- admonition
pages:
- Home: index.md
- Introduction: Introduction.md
- Preferences: Preferences.md
- Features:
  - Files and Folders.md
  - Applications and Processes.md
  - iTunes.md
  - Contacts.md
  - Mail.md
  - Chat.md
  - Calendar.md
  - Web.md
  - Text.md
  - Clipboard and Shelf.md
  - Note Taking Applications.md
  - Images.md
  - System.md
  - Development.md
- Appendix:
  - FAQ.md
  - Troubleshooting.md
  - Extending Quicksilver.md
  - Random Notes.md
  - Style Guide.md
- Plugins:
  - 1Password: plugins/onepassword.md
  - Abracadabra Triggers: plugins/gesturetriggers.md
  - Apple Mail: plugins/applemail.md
  - Automator: plugins/automator.md
  - Bezel Classic Interface: plugins/bezelclassicinterface.md
  - Calculator: plugins/tscalculator.md
  - Calendar: plugins/icalmodule.md
  - Chat Support: plugins/chatsupport.md
  - Clipboard: plugins/clipboard.md
  - Command Line Tool: plugins/commandlinetool.md
  - Contact Support: plugins/contactsupport.md
  - Contacts: plugins/addressbook.md
  - Cyberduck: plugins/cyberduck.md
  - Dash: plugins/dash.md
  - DeMinimizer: plugins/ytdemin.md
  - Developer: plugins/developer.md
  - Disk Image Support: plugins/diskimage.md
  - Displays: plugins/displays.md
  - E-mail Support: plugins/emailsupport.md
  - Event Triggers: plugins/eventtriggers.md
  - Extra Scripts: plugins/extrascripts.md
  - FaceTime: plugins/facetime.md
  - File Attribute: plugins/fileattributes.md
  - File Compression: plugins/compression.md
  - Firefox: plugins/firefox.md
  - Flashlight Interface: plugins/flashlightinterface.md
  - Gmail: plugins/gmail.md
  - Google Calendar Module: plugins/googlecalendar.md
  - Google Chrome: plugins/googlechrome.md
  - Growl Notifier: plugins/growl.md
  - Image Manipulation: plugins/imagemanipulation.md
  - Keychain: plugins/keychain.md
  - MailMate: plugins/mailmate.md
  - Menu Interface: plugins/menuinterface.md
  - Microsoft Office: plugins/microsoftoffice.md
  - Mini Interface: plugins/miniinterface.md
  - Mini-Bezel: plugins/minibezel.md
  - Mouse Triggers: plugins/mousetrigger.md
  - Networking: plugins/networking.md
  - Nostromo Interface: plugins/nostromointerface.md
  - Notification Hub: plugins/notificationhub.md
  - OmniWeb: plugins/omniweb.md
  - OpenMeta File Tagging: plugins/openmetafiletagging.md
  - Opera: plugins/opera.md
  - Path Finder: plugins/pathfinder.md
  - Process Manipulation: plugins/processmanipulation.md
  - PushDialer: plugins/quicksilver.md
  - QSQRCode: plugins/qrcode.md
  - Remember The Milk: plugins/rememberthemilk.md
  - Remote Hosts: plugins/remotehosts.md
  - Safari: plugins/safari.md
  - Screen Capture: plugins/screencapture.md
  - Services Menu: plugins/servicesmenu.md
  - Shelf: plugins/shelf.md
  - Showcase: plugins/showcase.md
  - Social Bookmarks: plugins/delicious.md
  - Spotlight: plugins/spotlight.md
  - System HotKey Commands: plugins/symbolichotkey.md
  - Terminal: plugins/terminal.md
  - Text Manipulation: plugins/textmanipulation.md
  - TextStart Ranker: plugins/textstartranker.md
  - Transmit 4: plugins/transmitmodule.md
  - Twitter: plugins/twit.md
  - User Interface: plugins/uiaccess.md
  - Viscosity: plugins/viscosity.md
  - VoodooPad Module: plugins/voodoopad.md
  - Web Search: plugins/websearch.md
  - White Bezel Interface: plugins/whitebezel.md
  - Window Interface: plugins/windowinterface.md
  - Yojimbo: plugins/yojimbo.md
  - iPhoto: plugins/iphoto.md
  - iTerm2: plugins/iterm2.md
  - iTunes: plugins/itunes.md
site_name: Quicksilver Manual
