edit_uri: edit/main/docs/
extra_css:
- css/qs.css
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 2-6
- md_in_html
nav:
- Home: index.md
- Getting Started:
  - Why Quicksilver: getting-started/why-quicksilver.md
  - Installation: getting-started/installation.md
  - Getting Started: getting-started/getting-started.md
  - Concepts and Terminology: getting-started/concepts-and-terminology.md
  - Invoking Quicksilver: getting-started/invoking-quicksilver.md
- Features:
  - Files and Folders.md
  - Applications and Processes.md
  - iTunes.md
  - Contacts.md
  - Mail.md
  - Chat.md
  - Calendar.md
  - Web.md
  - Text.md
  - Clipboard and Shelf.md
  - Note Taking Applications.md
  - Images.md
  - System.md
  - Development.md
- Plugins:
  - 1Password: plugins/onepassword.md
  - Abracadabra Triggers: plugins/gesturetriggers.md
  - Apple Mail: plugins/applemail.md
  - Audio: plugins/audio.md
  - Automator: plugins/automator.md
  - Calculator: plugins/tscalculator.md
  - Calendar & Reminders: plugins/icalmodule.md
  - Clipboard: plugins/clipboard.md
  - Command Line Tool: plugins/commandlinetool.md
  - Contacts: plugins/addressbook.md
  - Cyberduck: plugins/cyberduck.md
  - Dash: plugins/dash.md
  - DeMinimizer: plugins/ytdemin.md
  - Developer: plugins/developer.md
  - Displays: plugins/displays.md
  - E-mail Support: plugins/emailsupport.md
  - Emojis: plugins/emojisplugin.md
  - Event Triggers: plugins/eventtriggers.md
  - Extra Scripts: plugins/extrascripts.md
  - FaceTime: plugins/facetime.md
  - File Attribute: plugins/fileattributes.md
  - File Compression: plugins/compression.md
  - Firefox: plugins/firefox.md
  - Gmail: plugins/gmail.md
  - Google Chrome: plugins/googlechrome.md
  - Image Manipulation: plugins/imagemanipulation.md
  - iPhoto: plugins/iphoto.md
  - iTerm2: plugins/iterm2.md
  - iTunes: plugins/itunes.md
  - Keychain: plugins/keychain.md
  - MailMate: plugins/mailmate.md
  - Microsoft Office: plugins/microsoftoffice.md
  - Mouse Triggers: plugins/mousetrigger.md
  - Networking: plugins/networking.md
  - Nostromo Interface: plugins/nostromointerface.md
  - Notification Hub: plugins/notificationhub.md
  - OmniWeb: plugins/omniweb.md
  - OpenMeta File Tagging: plugins/openmetafiletagging.md
  - Opera: plugins/opera.md
  - Process Manipulation: plugins/processmanipulation.md
  - QSQRCode: plugins/qrcode.md
  - Remember The Milk: plugins/rememberthemilk.md
  - Remote Hosts: plugins/remotehosts.md
  - Safari: plugins/safari.md
  - Screen Capture: plugins/screencapture.md
  - Services Menu: plugins/servicesmenu.md
  - Shelf: plugins/shelf.md
  - Shortcuts: plugins/shortcutsplugin.md
  - Spotlight: plugins/spotlight.md
  - System HotKey Commands: plugins/symbolichotkey.md
  - Terminal: plugins/terminal.md
  - Text Manipulation: plugins/textmanipulation.md
  - Transmit 4: plugins/transmitmodule.md
  - Twitter: plugins/twit.md
  - User Interface: plugins/uiaccess.md
  - Viscosity: plugins/viscosity.md
  - Web Search: plugins/websearch.md
  - Yojimbo: plugins/yojimbo.md
  - Yosemite Interface: plugins/yosemite.md
  - zoom.us: plugins/zoom.md
- Preferences:
  - Overview: preferences/preferences.md
  - General: preferences/general.md
  - Catalog: preferences/catalog.md
  - Triggers: preferences/triggers.md
  - Using the Mouse: preferences/using-the-mouse.md
  - Touch Bar Support: preferences/touch-bar-support.md
  - Plugins: preferences/plugins.md
- Appendix:
  - FAQ.md
  - Troubleshooting.md
  - Extending Quicksilver.md
  - Random Notes.md
  - Style Guide.md
  - Search: search.md
plugins:
  - git-committers:
      repository: quicksilver/manual
      token: !ENV [GIT_COMMITTERS_TOKEN]
      enabled: !ENV [CI, false]
      exclude:
        - plugins/*
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago
  - search:
      lang: en
  - to-pdf:
      author: Howard Melman & Quicksilver Team
      cover_logo: https://qsapp.com/assets/quicksilver-icon-CpykCx5c.png
      cover_subtitle: by Howard Melman & Quicksilver Team
      download_link: footer
      enabled_if_env: CI
      output_path: pdf/quicksilver-manual.pdf
repo_url: https://github.com/quicksilver/manual
site_name: Quicksilver User Manual
site_url: https://qsapp.com/manual
theme:
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - search.suggest
  - search.highlight
  - content.action.edit
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  locale: en
  name: material
  palette:
  - accent: purple
    primary: custom
    scheme: light
  - accent: purple
    primary: custom
    scheme: dark
