edit_uri: edit/main/developer/docs/
extra_css:
- css/qs.css
markdown_extensions:
- toc:
    permalink: true
    toc_depth: 2-6
- md_in_html
nav:
- Home: index.md
- Project:
  - Helping Quicksilver: project/get-involved.md
  - Developer Information: project/Developer_Information.md
  - Github: project/Github.md
- App Development:
  - Building Quicksilver: app-development/Building_Quicksilver.md
  - Debugging Quicksilver: app-development/Debugging_Quicksilver.md
  - Unit Tests: app-development/UnitTests.md
  - Localization: app-development/Localization.md
  - Release Process: project/Release_Process.md
  - Quicksilver Server: app-development/Quicksilver_Server.md
  - Plugin Release Process: app-development/plugin-release-process.md
- Plugin Development:
  - Introduction: plugin-development/intro.md
  - Documentation: plugin-development/documentation.md
  - Reference:
    - Properties (Info.plist): plugin-development/reference/properties.md
    - Registration: plugin-development/reference/registration.md
    - Requirements: plugin-development/reference/requirements.md
    - QSObject: plugin-development/reference/qsobject.md
    - Proxies: plugin-development/reference/proxies.md
    - Preferences: plugin-development/reference/preferences.md
    - Events: plugin-development/reference/events.md
    - Commands: plugin-development/reference/commands.md
    - Resource Additions: plugin-development/reference/resource-additions.md
    - Trigger Presets: plugin-development/reference/trigger-presets.md
    - Scripting Bridge: plugin-development/scripting-bridge.md
  - Actions:
    - Concepts: plugin-development/actions/index.md
    - Properties: plugin-development/actions/properties.md
    - Validation: plugin-development/actions/validation.md
    - Combined Objects: plugin-development/actions/comma-trick.md
    - Alternates: plugin-development/actions/alternates-reverse.md
    - Other: plugin-development/actions/types.md
  - Catalog:
    - Concepts: plugin-development/catalog/index.md
    - Custom Types: plugin-development/catalog/custom-types.md
  - Notifications: plugin-development/Notifications.md
  - Upgrading Xibs: plugin-development/Upgrading_Xibs.md
  - Guides:
    - Troubleshooting: plugin-development/troubleshooting.md
    - AppleScript Examples:
      - Combine PDFs: plugin-development/guides/Combine_PDFs_(AppleScript).md
      - Open AirDrop: plugin-development/guides/Open_AirDrop_(AppleScript).md
      - Paste File Path: plugin-development/guides/Paste_file_path_(AppleScript).md
    - Convert Units To: plugin-development/guides/Convert_Units_To.md
    - Run Command: plugin-development/guides/Run_command_in_shell_with_arguments.md
plugins:
- git-revision-date-localized:
    fallback_to_build_date: true
    type: timeago
- search:
    lang: en
repo_url: https://github.com/quicksilver/manual
site_name: Quicksilver Developer Documentation
site_url: https://developer.qsapp.com/
theme:
  features:
  - navigation.instant
  - navigation.indexes
  - navigation.footer
  - content.action.edit
  - search.suggest
  - search.highlight
  - search.share
  logo: https://qsapp.com/assets/quicksilver-icon-CpykCx5c.png
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  locale: en
  name: material
  palette:
  - accent: purple
    primary: custom
    scheme: light
  - accent: purple
    primary: custom
